const BTC = require('./KnitBitcoin.json')
const ETH = require('./KnitEthereum.json')
const XLM = require('./KnitStellar.json')
const XRP = require('./KnitRipple.json')
const LTC = require('./KnitLitecoin.json')
const BCH = require('./KnitBitcoinCash.json')
const ZEC = require('./KnitZcash.json')
const DOGE = require('./KnitDogecoin.json')
const DASH = require('./KnitDash.json')
const BSV = require('./KnitBitcoinSV.json')
const TOMO = require('./KnitTomo.json')
const SC = require('./KnitTomo.json')
const FRONT = require('./KnitTomo.json')

export { BTC, ETH, XLM, XRP, LTC, BCH, ZEC, DOGE, DASH, BSV, TOMO, SC, FRONT }
